### PR TITLE
Add iterator version of begin/end for selection_t.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by sean-parent** [comment]
Is there a rational for this change? The selection_t type has a number of invariants that should be preserved at the class interface - I'd rather avoid providing a general iterator into the selection_t. I just finished writing a similar structure in JS - we should probably discuss naming and operations more on this implementation.

**Comment by ilelann** [comment]
Quite sure this has to do with Boost range concept checks.
Boost does checks for non const version of begin/end.

I disabled them in my "CMake build" commit 
https://github.com/stlab/adobe_source_libraries/commit/b8c98f3fd4361ad31fafd6763770d1d36362446c#diff-6be3438f3924f7603c82c8b35b066575R9

**Comment by ilelann** [comment]
Oh, and I just remembered I created an issue for this :)

https://github.com/stlab/adobe_source_libraries/issues/34

**Comment by ahmedcharles** [comment]
@ilelann is correct in that the motivation is fixing an error generated by Boost's range concepts.

There are other possible fixes, including changing the range concepts to require less, though that would require waiting for another release of Boost.

**Comment by ahmedcharles** [comment]
Is there another viable solution?

**Comment by sean-parent** [comment]
Got a bit sidetracked on this one - the begin.app is DOA with the latest Xcode which is my usual test app - I'll try and get something togther today for testing but my question is where is this triggering the concept check errors and can we fix at that location - possibly by using std::begin()/end() or cbegin()/end()?

**Comment by ilelann** [comment]
What cause the concept check to fail is boost::range_size<Selection>::type.
By replacing this with Selection::size_type, and boost::size(s) calls with s.size(), one can restore BOOST_RANGE_ENABLE_CONCEPT_ASSERT

**Comment by alexk7** [comment]
This is more elegantly solved by simply defining iterator to be the same as const_iterator. That's the way I fixed the problem in #46

**Comment by sean-parent** [comment]
@alexk7: Thanks - I agree with that change. Closing this one out.

**Pull request closed without merging**
