### PR TITLE
cmake fixes

### PR DESCRIPTION
**Pull request by ilelann**
On my Fedora, I have no BOOST_ROOT defined and Boost is split into /usr/include and /usr/lib64
So I changed to an explicit flag asking to use find_package (which is supposed to detect BOOST_ROOT, if present)

ctest usage in sh scripts is to run BENCHMARK tests in Release mode only.

The shift_down template is to silence an arguable GCC warning on potential shift overflow.
GCC does not detect that the "constexpr if" prevents that ... With template, offending code is not instantiated.

### CODE REVIEW

**Comment by ilelann** [comment]
OK. No thread_local in XCode's Clang. 
I will probably repush later without the boost thread related commit.

**Comment by sean-parent** [comment]
You are hitting the issue on Travis that Mac (still!) doesn't support thread_local.

**Comment by ilelann** [comment]
Repushed. I basically merged the two CMake related commits and removed the boost thread one.

**Comment by ilelann** [comment]
Repushed with some changes on double-conversion as discussed here https://github.com/stlab/adobe_source_libraries/pull/41

**Comment by fosterbrereton** [comment]
Looks good to me. @sean-parent?

**Comment by ilelann** [comment]
Repushed a commit for minor issues that hit me when working on APL

**Pull request merged**
